
yelp_consumer_key: "9tC86EYrqcc5w6JQBRwU6A"
yelp_consumer_secret: "eU_jP7cu-_Oovr1Mni7ZjgsZKyw"
yelp_token: "Z2-G83w9cVy-DiqBR75hHMe-GzZwarDL"
yelp_token_secret: "vfTxK8VYEW3rqXLLlYiwe_HBpV8"
ngrok_url: "http://33e8b37a.ngrok.com/typeform_results"
typeform_api_token: "56e3b81325add8b5f48645d27eaf7fd3"